# .readthedocs.yaml
version: 2

sphinx:
  configuration: source/conf.py

python:
  version: "3.13" 
  install:
    - method: pip

build:
  image: latest
  tools:
    python: "3.13"

sphinx_build:
  builder: html
  source_directory: source
  output_directory: build/html
